#!/bin/bash
# Booking Bandit Local Claude Engine (Beta) - macOS installer.
#
# Registers the native-messaging host so Chrome can spawn it for the pinned beta
# extension. Idempotent: re-run any time to update files or repair the registration.
#
# Usage (from anywhere):
#   bash "<repo>/production-build/local-engine/install/install-mac.sh" [EXTENSION_ID]
#
# EXTENSION_ID defaults to the pinned beta ID. Pass a different one to override.
#
# macOS vs Windows: the manifest is a FILE under the browser's NativeMessagingHosts
# directory (no registry), the launcher is an executable shell script (not a .bat),
# and a GUI-launched browser inherits a stripped PATH - so the launcher pins both the
# absolute node binary AND node's dir onto PATH, so `claude`'s `#!/usr/bin/env node`
# shebang still resolves when the host spawns it.

set -euo pipefail

HOST_NAME="com.bookingbandit.localengine"
EXT_ID="${1:-eoaibojoneilhiagjmmhbbgehnmloelj}"

# --- Resolve source + install locations ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"       # .../local-engine/install
SRC_DIR="$(dirname "$SCRIPT_DIR")"                # .../local-engine
INSTALL_DIR="$HOME/Library/Application Support/BookingBandit"
WORK_DIR="$INSTALL_DIR/workdir"
LAUNCHER="$INSTALL_DIR/booking-bandit-host.sh"
MANIFEST_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
MANIFEST_PATH="$MANIFEST_DIR/$HOST_NAME.json"

echo "Installing Booking Bandit Local Engine host (macOS)..."
echo "  source : $SRC_DIR"
echo "  target : $INSTALL_DIR"

# --- Copy runtime files ---
mkdir -p "$INSTALL_DIR/host" "$WORK_DIR" "$MANIFEST_DIR"
cp "$SRC_DIR/contract.mjs"   "$INSTALL_DIR/contract.mjs"
cp "$SRC_DIR/host/main.mjs"  "$INSTALL_DIR/host/main.mjs"

# --- Preflight: node must exist; pin its absolute path + dir ---
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "ERROR: Node.js not found on PATH. Install Node (>=18), then re-run this installer." >&2
  exit 1
fi
NODE_BIN="$(cd "$(dirname "$NODE_BIN")" && pwd)/$(basename "$NODE_BIN")"  # absolutize
NODE_DIR="$(dirname "$NODE_BIN")"
echo "  node   : $NODE_BIN (pinned into launcher)"

# --- Preflight: claude must exist; cache its absolute path (host reads this first) ---
CLAUDE_BIN="$(command -v claude || true)"
if [ -z "$CLAUDE_BIN" ]; then
  echo "ERROR: Claude Code (claude) not found on PATH. Install Claude Code and sign in first." >&2
  exit 1
fi
CLAUDE_BIN="$(cd "$(dirname "$CLAUDE_BIN")" && pwd)/$(basename "$CLAUDE_BIN")"  # absolutize
printf '%s' "$CLAUDE_BIN" > "$WORK_DIR/claude-path.txt"
echo "  claude : $CLAUDE_BIN"
if CLAUDE_VER="$(claude --version 2>/dev/null)"; then
  echo "  claude --version -> $CLAUDE_VER"
else
  echo "  WARNING: could not run 'claude --version' - make sure Claude Code is installed and signed in." >&2
fi

# --- Generate the launcher (node + PATH pinned) ---
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Booking Bandit Local Claude Engine - native-messaging host launcher (macOS).
# GENERATED by install-mac.sh (node path + dir pinned at install time).
# Chrome execs THIS file; it hands stdin/stdout straight to the Node host. PATH is
# pinned so a GUI-launched browser (stripped PATH) can still resolve node + claude.
export PATH="$NODE_DIR:\$PATH"
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
exec "$NODE_BIN" "\$DIR/host/main.mjs" "\$@"
EOF
chmod 755 "$LAUNCHER"
echo "  launcher: $LAUNCHER"

# --- Write the host manifest (file-based; Chrome reads this directory) ---
cat > "$MANIFEST_PATH" <<EOF
{
  "name": "$HOST_NAME",
  "description": "Booking Bandit Local Claude Engine (Beta) native host",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXT_ID/"
  ]
}
EOF
echo "  manifest: $MANIFEST_PATH  [Chrome]"

# --- Verification: spawn the INSTALLED launcher exactly like Chrome does and demand
# a framed pong. "Installer exited 0" != "the engine works".
echo ""
echo "Verifying the installed host (framed ping through $LAUNCHER)..."
if ! "$NODE_BIN" "$SRC_DIR/scripts/smoke-host.mjs" --ping --host "$LAUNCHER"; then
  echo "ERROR: Installed-host verification FAILED (see output above). Run install/doctor-mac.sh for a full diagnosis." >&2
  exit 1
fi

echo ""
echo "Done. Native host '$HOST_NAME' registered (Chrome) for extension $EXT_ID - verified end-to-end."
echo "If Chrome is open, FULLY quit it (Cmd-Q, or check the menu bar - closing the window is not enough) and reopen it so it re-reads the manifest."
