# Booking Bandit Local Claude Engine (Beta) - Windows installer.
#
# Registers the native-messaging host so Chrome can spawn it for the pinned beta
# extension. Idempotent: re-run any time to update files or repair the registration.
#
# Usage (from the local-engine folder):
#   powershell -ExecutionPolicy Bypass -File install\install-windows.ps1 -ExtensionId <PINNED_BETA_ID>
#
# The ExtensionId is the beta extension's stable ID (pinned via manifest key).

param(
  [Parameter(Mandatory = $true)]
  [string]$ExtensionId,
  # Which browser's native-messaging registry to register under. Chromium forks
  # each read a DIFFERENT HKCU path (the manifest + host files are shared).
  # 'all' = every known hive (Chrome + Comet both variants + Edge + Chromium) -
  # registering an unused hive is harmless, missing one is a dead helper.
  [ValidateSet('chrome', 'comet', 'edge', 'both', 'all')]
  [string]$Browser = 'all'
)

$ErrorActionPreference = 'Stop'
$HostName = 'com.bookingbandit.localengine'

# --- Resolve source + install locations ---
$SrcDir     = Split-Path -Parent $PSScriptRoot            # ...\local-engine
$InstallDir = Join-Path $env:LOCALAPPDATA 'BookingBandit'
$WorkDir    = Join-Path $InstallDir 'workdir'
$HostBat    = Join-Path $InstallDir 'booking-bandit-host.bat'
$ManifestPath = Join-Path $InstallDir "$HostName.json"

Write-Host "Installing Booking Bandit Local Engine host..." -ForegroundColor Cyan
Write-Host "  source : $SrcDir"
Write-Host "  target : $InstallDir"

# --- Copy runtime files ---
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $InstallDir 'host') | Out-Null
New-Item -ItemType Directory -Force -Path $WorkDir | Out-Null

Copy-Item (Join-Path $SrcDir 'contract.mjs')            -Destination $InstallDir -Force
Copy-Item (Join-Path $SrcDir 'host\main.mjs')           -Destination (Join-Path $InstallDir 'host') -Force

# --- Preflight: Node + claude must exist ---
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) { throw "Node.js not found on PATH. Install Node (>=18), then re-run this installer." }

# Pin the absolute node.exe into the launcher so the host survives a browser
# spawned with a stripped PATH (GUI-launch environments differ from terminals).
$nodeExe = $node.Source
@"
@echo off
rem Booking Bandit Local Claude Engine - native-messaging host launcher.
rem GENERATED by install-windows.ps1 (node path pinned at install time).
rem Chrome registers THIS file; it hands stdin/stdout straight to the Node host.
"$nodeExe" "%~dp0host\main.mjs" %*
"@ | Set-Content -Path $HostBat -Encoding ascii
Write-Host "  node   : $nodeExe (pinned into launcher)"

$claudeCmd = Get-Command claude -ErrorAction SilentlyContinue
if (-not $claudeCmd) { throw "Claude Code (claude) not found on PATH. Install Claude Code and sign in first." }

# Need a real .exe for the shell:false spawn (preserves the empty --setting-sources
# arg; Node can't spawn a .cmd shim with shell:false). The npm-global shim wraps a
# bundled native launcher - resolve to it. HARD-FAIL if no .exe resolves: caching a
# .cmd here guarantees a future spawn EINVAL (the exact landmine this replaces).
$claudePath = $claudeCmd.Source
if ($claudePath -notlike '*.exe') {
  $bundled = Join-Path (Split-Path -Parent $claudePath) 'node_modules\@anthropic-ai\claude-code\bin\claude.exe'
  if (Test-Path $bundled) {
    $claudePath = $bundled
  } else {
    throw "Found '$claudePath' but no spawnable claude.exe beside it. Reinstall Claude Code (npm i -g @anthropic-ai/claude-code), then re-run this installer."
  }
}
Set-Content -Path (Join-Path $WorkDir 'claude-path.txt') -Value $claudePath -Encoding utf8 -NoNewline
Write-Host "  claude : $claudePath"

try {
  $ver = & claude --version 2>$null
  Write-Host "  claude --version -> $ver"
} catch {
  Write-Warning "Could not run 'claude --version'. Make sure Claude Code is installed and signed in."
}

# --- Write the host manifest (ConvertTo-Json handles path backslash escaping) ---
$manifestObj = [ordered]@{
  name            = $HostName
  description     = 'Booking Bandit Local Claude Engine (Beta) native host'
  path            = $HostBat
  type            = 'stdio'
  allowed_origins = @("chrome-extension://$ExtensionId/")
}
$manifestObj | ConvertTo-Json | Set-Content -Path $ManifestPath -Encoding utf8
Write-Host "  manifest: $ManifestPath"

# --- Register in HKCU so the browser finds the host ---
# Each Chromium fork reads native-messaging hosts from its own product registry
# path (the one it also uses for BLBeacon/PreferenceMACs). Comet = Perplexity\Comet.
$vendorRoots = switch ($Browser) {
  'chrome' { @('Google\Chrome') }
  'edge'   { @('Microsoft\Edge') }
  'comet'  { @('Perplexity\Comet', 'Comet') }   # both, so whichever Comet build uses is covered
  'both'   { @('Google\Chrome', 'Perplexity\Comet', 'Comet') }
  'all'    { @('Google\Chrome', 'Perplexity\Comet', 'Comet', 'Microsoft\Edge', 'Chromium') }
}
foreach ($root in $vendorRoots) {
  $RegKey = "HKCU:\Software\$root\NativeMessagingHosts\$HostName"
  New-Item -Path $RegKey -Force | Out-Null
  Set-ItemProperty -Path $RegKey -Name '(default)' -Value $ManifestPath
  # Read it back - a silently-failed registry write is a dead helper later.
  $readback = (Get-ItemProperty -Path $RegKey -ErrorAction Stop).'(default)'
  if ($readback -ne $ManifestPath) { throw "Registry readback mismatch at $RegKey ('$readback' != '$ManifestPath')." }
  Write-Host "  registry: $RegKey  [verified]"
}

# --- Verification: spawn the INSTALLED host exactly like Chrome does (the .bat via
# cmd) and demand a framed pong. "Installer exited 0" != "the engine works" - this is
# the difference.
Write-Host ""
Write-Host "Verifying the installed host (framed ping through $HostBat)..." -ForegroundColor Cyan
$smoke = Join-Path $SrcDir 'scripts\smoke-host.mjs'
& $nodeExe $smoke --ping --host $HostBat
if ($LASTEXITCODE -ne 0) {
  throw "Installed-host verification FAILED (see output above). Run install\doctor-windows.ps1 for a full diagnosis."
}

Write-Host ""
Write-Host "Done. Native host '$HostName' registered ($Browser) for extension $ExtensionId - verified end-to-end." -ForegroundColor Green
Write-Host "If the browser is open, FULLY quit it (check the tray / Task Manager - closing the window is not enough for Comet) and reopen it so it re-reads the registry." -ForegroundColor Yellow
